[package]
name = "kash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
needletail ="0.5.1"
kodama = "0.3.0"
rayon = "1.7.0"
serde = "1.0"
serde-pickle = "1.0"